{% set name = "csdms-sedflux-avulsion" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/sedflux
  git_branch: add-function-pointers

requirements:
  build:
    - bmi-babel
    - sedflux
  run:
    - bmi-babel
    - sedflux

test:
  requires:
    - pymt

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  summary: A river avulsion model
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux
