language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: a83Qiy1Zn7xdpOBI0ND6xpS3ckITZxn48X4W96y7Cvufv2GWMbvzp74gSrumz7qnIzja6GQkbxScrUrF7+u5Oe0ws+MMBfLGdiIU9L/7YEv1SsPnHgcnQqRRR3FiajEsBS5Fe5PQ8h58MRIZBLgCEBfVAN3aXdcRnkQnEjAT+yHj9caxDhGprUSV7aCIGoVhG6YWu4xR7lEYjRIxZ3ugat2gMWNiww4AsdW4CflUVJaL9o791zTKnGQck0PvXe4GlBniC2KEa2N3ubclgtVeITJFhP45XXaK2Gn5f1mAFWd090MstlfIM2qRwY14oU868vw+vl8U7NJU0Ui9Obb/szWcmW4Ua3m3CTrwnCvHHr/6ZCMZiF/QDEq9ih5KhPNjo5tVaHUrYTI+SSHninOefL9FlfLX7vT/eUy7+GWushe/f8VldYI3qfsju7FPCjDlhTP630Yffj4PUtT9JL33r8qPLofEP0YCdppVBXrW25i1gevfws/fz41dhfjqmRkLnsyVW42OEHdSLVLHWzUNYBLb7cu63tfL142+XqJLoYc7FnBrXjRe9cbAPvC8/tWV/8Pi18htyx5Z5mw6F+a2Uq83pLaj+WksK/FP88cMqW0B4qi/sMnOPz8Aczdu0u07o+b+awn5XVZAsNK51j7CTyG4sFOFjJQ2ytru86iOliE=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
